name: result_in_dart
description: Result in Dart is a Dart package that provides a Result type for modeling success or failure operations.
version: 1.0.0
repository: https://github.com/devhammed/result_in_dart

environment:
  sdk: ^3.0.5

dev_dependencies:
  lints: ^2.0.0
